# .goreleaser.yml
version: 2

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/speedtest_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# Single, clean Docker configuration.
# GoReleaser automatically uses the 'linux' binaries from the build matrix above.
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
    # Specify which architectures from the build matrix to use for Docker.
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-armv7"

  - name_template: "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"

  - name_template: "c0mmandercrud/{{.ProjectName}}:latest"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"
