# .goreleaser.yml
version: 1
project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  # A single build for linux/amd64 that Docker will use
  - id: linux-amd64
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "linux" ]
    goarch: [ "amd64" ]

dockers:
  # This block implicitly uses the linux/amd64 build from above.
  # It does NOT use a 'builds:' key.
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}"
      - "c0mmandercrud/{{ .ProjectName }}:latest-snapshot"

# docker_manifests is not needed for a single docker image
