# .goreleaser.yml
version: 1

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/speedtest_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# This section is now a list of three separate Docker builds.
# Each item targets a single architecture.
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
    goos: linux
    goarch: arm64
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
    goos: linux
    goarch: arm
    goarm: '7'

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-armv7"
  - name_template: "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"
  - name_template: "c0mmandercrud/{{.ProjectName}}:latest"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"
