version: 1

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

# We now have a dedicated build block for each Linux architecture.
builds:
  - id: linux-amd64
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "linux" ]
    goarch: [ "amd64" ]
  - id: linux-arm64
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "linux" ]
    goarch: [ "arm64" ]
  - id: linux-armv7
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "linux" ]
    goarch: [ "arm" ]
    goarm: [ "7" ]
  # A separate build for non-docker archives
  - id: other-archives
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "windows", "darwin" ]
    goarch: [ "amd64" ]

archives:
  - id: default
    # This will now use all the builds defined above
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# Each docker entry now implicitly matches one of the simple build blocks above.
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"
  - goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-{{ .Arch }}"
      - "c0mmandercrud/{{ .ProjectName }}:v{{ .Version }}-{{ .Arch }}"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .ShortCommit }}-armv7"
  - name_template: "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"
  - name_template: "c0mmandercrud/{{.ProjectName}}:latest"
    image_templates:
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-amd64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-arm64"
      - "c0mmandercrud/{{.ProjectName}}:v{{ .Version }}-armv7"
