# .goreleaser.yml
version: 1
project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  # A single build for linux/amd64 that Docker will use
  - id: linux-amd64
    main: ./cmd/speedtest_exporter/main.go
    env: [ "CGO_ENABLED=0" ]
    goos: [ "linux" ]
    goarch: [ "amd64" ]

# .goreleaser.yml
dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    image_templates:
      # Use the GITHUB_REPOSITORY_OWNER environment variable for correctness
      # The | lower filter is required as image names must be lowercase
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | lower }}/{{ .ProjectName }}:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | lower }}/{{ .ProjectName }}:{{ .Version }}"
